# Generated by Django 4.1.5 on 2023-01-12 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antarestardata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='jumlah',
        ),
    ]
