# Generated by Django 3.2.16 on 2023-01-13 11:00

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('antarestardata', '0003_preorder_jumlah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='jumlah',
            field=models.CharField(default=django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('qty'), '*', django.db.models.expressions.F('harga')), max_length=100),
        ),
    ]
