# Generated by Django 3.2.16 on 2023-01-13 11:04

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('antarestardata', '0006_auto_20230113_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='harga',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='jumlah',
            field=models.IntegerField(default=django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('harga'), '*', django.db.models.expressions.F('qty'))),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='qty',
            field=models.IntegerField(null=True),
        ),
    ]
