# Generated by Django 3.2.16 on 2023-01-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antarestardata', '0009_alter_preorder_jumlah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='jumlah',
        ),
    ]
